import assert from 'node:assert/strict'
import { CLUES, STORY, OBJECTIVES, SUPPLIES, KEY_SUPPLY_GOAL, NPCS, QUESTS, QUEST_OBJECTS, QUEST_GOAL } from '../src/gameData.js'
assert.equal(CLUES.length, 3, '必须有三个环境线索')
assert.equal(new Set(CLUES.map(c => c.id)).size, 3, '线索 ID 必须唯一')
assert.ok(CLUES.every(c => c.position.length === 3 && c.position[2] < 0), '线索必须放置在纵深空间中')
assert.ok(CLUES[2].position[2] < CLUES[1].position[2], '第三线索应位于威胁段落之后')
assert.equal(OBJECTIVES.length, 6, '目标应覆盖探索、潜行、确认和同步')
assert.ok(OBJECTIVES.some(o => o.includes('回收 3 份关键补给')), '目标应包含关键补给回收')
assert.ok(STORY.threat.length && STORY.meeting.length && STORY.ending.synced, '关键叙事节点缺失')
// 物资搜寻系统
assert.ok(SUPPLIES.length >= 6, '至少布置 6 个物资点')
assert.equal(new Set(SUPPLIES.map(s => s.id)).size, SUPPLIES.length, '物资 ID 必须唯一')
assert.ok(SUPPLIES.every(s => s.position.length === 3 && s.position[2] < 0), '物资必须放置在纵深空间中')
assert.ok(SUPPLIES.filter(s => s.key).length >= 3, '至少 3 份关键补给')
assert.equal(KEY_SUPPLY_GOAL, 3, '关键补给目标为 3')
assert.ok(SUPPLIES.some(s => s.lore), '至少一份物资附带叙事碎片')
assert.ok(SUPPLIES.some(s => s.crouch || s.time_crouch), '至少一份物资需要蹲下搜寻')
assert.ok(STORY.ending.locked && STORY.ending.partial && STORY.ending.synced, '结局需含锁定/半程/同步三种分支')
// ---- NPC 与任务系统 ----
assert.ok(NPCS.length >= 3, '至少 3 位可对话 NPC')
assert.equal(new Set(NPCS.map(n => n.id)).size, NPCS.length, 'NPC ID 必须唯一')
assert.ok(NPCS.every(n => n.position.length === 3 && n.position[2] < 0), 'NPC 必须放置在纵深空间中')
assert.ok(NPCS.every(n => QUESTS.some(q => q.id === n.quest)), '每位 NPC 必须绑定任务')
assert.equal(QUESTS.length, 3, '至少 3 条任务线')
assert.equal(QUEST_GOAL, QUESTS.length, '任务完成度目标应等于任务总数')
assert.deepEqual([...new Set(QUESTS.map(q => q.type))].sort(), ['collect', 'locate', 'operate'], '任务需覆盖收集/定位/操作三种类型')
assert.ok(QUESTS.every(q => q.offer.length && q.turnIn.length && q.brief && q.log), '任务需含接取/回报对话与日志描述')
assert.ok(QUESTS.every(q => q.reward && q.reward.item), '每条任务需要奖励')
assert.ok(QUESTS.find(q => q.type === 'collect').need.item === '医疗包', '收集任务需交付医疗包')
assert.ok(SUPPLIES.filter(s => s.item === '医疗包').length >= 2, '场景中需有可供交付的医疗包')
assert.equal(QUEST_OBJECTS.beacons.length, QUESTS.find(q => q.targets === 'beacons').goal, '信标数量需与定位任务目标一致')
assert.equal(QUEST_OBJECTS.consoles.length, QUESTS.find(q => q.targets === 'consoles').goal, '中继台数量需与操作任务目标一致')
assert.ok(QUESTS.some(q => q.choices && q.choices.length >= 2), '对话需提供分支选项')
assert.ok(STORY.ending.deeper, '全任务完成需有专属结局')
console.log('数据检查通过：3 线索 / 7 物资(≥3 关键) / 3 NPC / 3 任务(收集·定位·操作) / 四结局')
