import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const world = readFileSync(new URL('../src/World3D.jsx', import.meta.url), 'utf8')
const app = readFileSync(new URL('../src/main.jsx', import.meta.url), 'utf8')
const pbr = readFileSync(new URL('../src/pbr.js', import.meta.url), 'utf8')
for (const token of ['requestPointerLock', 'KeyW', 'KeyA', 'KeyS', 'KeyD', 'ShiftLeft', 'KeyC', 'KeyE', 'KeyQ', 'KeyR']) assert.ok(world.includes(token), `缺少第一人称控制：${token}`)
for (const token of ['FogExp2', 'SpotLight', 'PointLight', 'Points', 'PerspectiveCamera']) assert.ok(world.includes(token), `缺少 3D 氛围能力：${token}`)
// 视觉质感升级
for (const token of ['EffectComposer', 'UnrealBloomPass', 'makePBRMaterial', 'InstancedMesh', 'PMREMGenerator', 'LoadingManager']) assert.ok(world.includes(token), `缺少视觉升级能力：${token}`)
assert.ok(pbr.includes('normalMap') && pbr.includes('roughnessMap'), 'PBR 法线/粗糙度生成缺失')
// 物资搜寻系统
assert.ok(world.includes('SUPPLIES') && world.includes('searching') && world.includes('onCollect'), '物资搜寻逻辑未连接')
assert.ok(app.includes('collected') && app.includes('inventory') && app.includes('KEY_SUPPLY_GOAL'), '背包/关键补给未连接')
assert.ok(app.includes("'partial'") && app.includes("'synced'"), '结局分支未连接')
assert.ok(world.includes('onSafe') && world.includes('hidden >= 3'), '潜行压力段落未连接')
assert.ok(world.includes('onConfirm') && app.includes('qteHit'), '扫描确认或 QTE 未连接')
assert.ok(app.includes('setPaused') && app.includes('reset'), '暂停或重新开始未连接')
assert.ok(app.includes('AtmosAudio') && app.includes('toggleMute'), '程序化音频或静音未连接')
// 交互链路修复：鼠标左键触发交互 + 长按搜寻，提示与执行一致
assert.ok(world.includes('mousedown') && world.includes('mouseHeld'), '鼠标左键交互未连接')
assert.ok(/mouseHeld[^]*interact\(\)/.test(world.replace(/\n/g,'')) || world.includes('interact(); if'), '左键未触发交互')
assert.ok(world.includes('keys.KeyR || state.searchHeld || mouseHeld'), '左键长按搜寻未连接')
// 威胁生物贴图化重制：billboard impostor / 多姿态 / alpha / 红光反馈 / 远景巨物
const audio = readFileSync(new URL('../src/audio.js', import.meta.url), 'utf8')
for (const token of ['beast_walk', 'beast_alert', 'beast_lunge', 'colossus']) assert.ok(world.includes(token), `缺少怪物贴图素材：${token}`)
assert.ok(world.includes('beastPoses') && world.includes('alphaTest'), '怪物 billboard/alpha 未连接')
assert.ok(world.includes("poseKey = wantPose") && world.includes("'lunge'") && world.includes("'alert'"), '怪物多姿态切换未连接')
assert.ok(world.includes('dangerPlane') && world.includes('dangerLevel'), '发现玩家红闪/震动反馈未连接')
assert.ok(world.includes('beastGlow') && world.includes('AdditiveBlending'), '怪物荧光辉光未连接')
assert.ok(audio.includes('growl'), '怪物低吼音效未连接')
assert.ok(!world.includes('CapsuleGeometry'), '旧的简陋几何体怪物未移除')
// ---- Blender 真实 3D 资产管线 ----
import { existsSync, readdirSync } from 'node:fs'
const modelsDir = new URL('../src/assets/models/', import.meta.url)
assert.ok(existsSync(modelsDir), 'Blender 导出的模型目录缺失')
const glbs = readdirSync(modelsDir).filter(f => f.endsWith('.glb'))
assert.ok(glbs.length >= 10, `Blender 资产数量不足：${glbs.length}`)
for (const f of ['tunnel_module.glb', 'station_hall.glb', 'prop_container.glb', 'prop_console.glb', 'prop_beacon.glb']) assert.ok(glbs.includes(f), `缺少关键 Blender 资产：${f}`)
assert.ok(existsSync(new URL('../tools/blender/build_assets.py', import.meta.url)), 'Blender 建模脚本缺失')
assert.ok(world.includes('GLTFLoader') && world.includes('.glb'), 'GLTFLoader 未接入')
assert.ok(world.includes('instanceGLB') && world.includes('placeGLB'), 'GLB 实例化/单体摆放未连接')
assert.ok(world.includes('MAT_CONCRETE') && world.includes('slotOf'), 'GLB 材质插槽未映射到项目 PBR 材质')
// ---- NPC 与任务互动系统 ----
assert.ok(world.includes('NPCS') && world.includes('onTalk') && world.includes('nearestNPC'), 'NPC 对话交互未连接')
assert.ok(world.includes('npc_ranger') && world.includes('npc_operator'), 'NPC 立绘资源未接入')
assert.ok(world.includes('onScanTarget') && world.includes('onActivate'), '任务扫描/操作回调未连接')
assert.ok(world.includes('QUEST_OBJECTS') && world.includes('beaconNodes') && world.includes('consoleNodes'), '任务交互物未布置到场景')
assert.ok(world.includes('trackTarget') && world.includes('guide'), '任务方向指引未连接')
assert.ok(app.includes('QUESTS') && app.includes('setQuests') && app.includes('finishDialog'), '任务状态机未连接')
assert.ok(app.includes('advanceDialog') && app.includes('pickChoice'), '对话推进/分支选择未连接')
assert.ok(app.includes('questLog') && app.includes("'KeyJ'"), '任务日志与快捷键未连接')
assert.ok(app.includes('compass'), '罗盘方向指引 UI 未连接')
assert.ok(app.includes("'deeper'") && app.includes('questsDone>=QUEST_GOAL'), '任务完成度未影响结局')
console.log('交互代码检查通过：Pointer Lock / WASD / 潜行 / QTE / PBR / Bloom / 物资搜寻 / 怪物贴图化 / Blender GLB 资产 / NPC 对话 / 任务系统 / 方向指引')
